@startuml

actor AFP as AFP

AFP -> Sistema : gerenciarInformacoes()
AFP <-- Sistema : solicita operação

opt Adicionar
    AFP -> Sistema : adicionarFuncionario()
    AFP <-- Sistema : solicita informações
    AFP -> Sistema : inserirInformacoes(nome, tipoFun, endereco, deducoes, tel, taxa, salario, comissao, limiteHoras)
    Sistema -> Sistema: gera e atribui ID para o funcionário
    Sistema -> Sistema: define metodo de entrega como "retirada
    Sistema -> Sistema: adiciona funcionário
    AFP <-- Sistema: envia ID do funcionário
else Atualizar
    AFP -> Sistema : atualizarFuncionario()
    AFP <-- Sistema : solicita ID do funcionário
    AFP -> Sistema : inserirIDFuncionario(ID)
    alt Funcionário não encontrado
        AFP <-- Sistema : mensagem de erro avisando que o funcionário não existe
        opt
            AFP -> Sistema : inserirIDFuncionario(ID)
        else
            AFP -> Sistema : cancelar()
        end
    end
    AFP <-- Sistema : retorna informações do funcionário
    AFP -> Sistema : alterarInformacoes(nome, tipoFun, endereco, deducoes, tel, taxa, salario, comissao, limiteHoras)
    Sistema -> Sistema: atualiza funcionário
else Excluir
    AFP -> Sistema : excluirFuncionario()
    AFP <-- Sistema : solicita ID do funcionário
    AFP -> Sistema : inserirIDFuncionario(ID)
    alt Funcionário não encontrado
        AFP <-- Sistema : mensagem de erro avisando que o funcionário não existe
        opt
            AFP -> Sistema : inserirIDFuncionario(ID)
        else
            AFP -> Sistema : cancelar()
        end
    end
    AFP <-- Sistema : solicita confirmação da operação
    alt Cancelar exclusão
         AFP -> Sistema : cancelar()
    end
    AFP -> Sistema : confirmar()
    Sistema -> Sistema : marca a exclusão do funcionário
end

@enduml