@startuml caso8
actor RelogioSistema as RelogioSistema
Participant "folha: FolhaDePagamento" as fdp
Participant "pgto: Pagamento" as pagamento
Participant "gerente: Gerente" as gerente
Participant "empresa : Empresa" as empresa
Participant "listaFun : ListaDefuncionarios" as listafuncionarios
Participant "func: funcionario" as funcionario
Participant "ponto: Ponto" as ponto

activate RelogioSistema
RelogioSistema  -> fdp : executarFolhaPagamento()
loop 
    activate fdp
    loop pag in pagamentos
        fdp -> pagamento : pagFun.append(getPagamento())
        activate pagamento
    end
    deactivate pagamento

    loop
        fdp -> gerente: horas.append(getHoras(pagFun.fun))
        activate gerente
        gerente -> empresa: procuraFunc(pagFun.fun)
        activate empresa
        empresa -> listafuncionarios: getFunc(pagFun.fun)
        activate listafuncionarios
        loop ponto in pagFun.fun
            empresa -> funcionario: horas += somaHoras()
            activate funcionario
            funcionario -> ponto: retornaHoras()
            activate ponto
            deactivate ponto
        end
        deactivate funcionario

        deactivate listafuncionarios
        deactivate empresa
        deactivate gerente
    end

    loop pag in pagFun
        fdp -> fdp : trans = calculaPagamento(pagFun)
        fdp -> fdp: enviaTransacao(trans)
    end

end
@enduml