@startuml caso8

RelogioSistema  -> Sistema : executarFolhaPagamento()
Sistema   --> Sistema : recupera funcionarios a serem pagos

loop todos os funcionarios foram pagos
    Sistema   --> Sistema : recupera folhas ponto
    Sistema   --> Sistema : recupera ordens de compra
    Sistema   --> Sistema : recupera informações do usuario
    Sistema   --> Sistema : realiza deduçoes legais
    
    alt pagamento é feito via correio
        Sistema   --> Sistema : cria transacao bancaria
        Sistema   --> Correios     : envia ordem de pagamento
    else pagamentos é feito via deposito bancário
        Sistema   --> Sistema : cria transacao bancaria
        Sistema   --> SistemaBanco : envia ordem de pagamento
        alt sistema bancario indisponivel
            loop sistema bancario indisponivel
                Sistema   --> Sistema      : aguarda determinado periodo
                Sistema   --> SistemaBanco : tenta enviar a ordem de pagamento novamente
            end
    end

    opt id do funcionario foi marcado como excluido
        Sistema   --> Sistema : excluir funcionario
    end
end


@enduml