@startuml
Actor AdmFP as AFP

AFP -> Sistema : solicitaRelatorioAdm()
AFP <-- Sistema : pede especificações do relatório
AFP -> Sistema : criaRelatorioAdm(tipoRelat, dataIni, dataFim, nomesFunc)

alt Informações Encontradas

    Sistema <-- Sistema : cria o relatório solicitado
    AFP <-- Sistema : devolve o relatório solicitado
    alt Salvar

        AFP -> Sistema : solicitaSalvamentoRelatorio(relat)
        AFP <-- Sistema : solicita o nome e o local para o salvamento
        AFP -> Sistema : salvaRelatorio(relat, nome, local)
        AFP <-- Sistema : pede confirmação
        AFP -> Sistema : confirmaAcao()
        AFP <-- Sistema : salva o relatório com o nome e local especificado e termina a execução

    else Não Salvar

        AFP -> Sistema : descartaRelatorio(relat)
        AFP <-- Sistema : notifica o descarte
        Sistema <-- Sistema : descarta o relatório e termina a execução

    end

else Informações Indisponíveis

    AFP <-- Sistema : mensagem de erro informando a indisponibilidade das informações
    alt Inicio

        AFP -> Sistema : retornaTelaIni()
        AFP <-- Sistema : volta para a tela de início

    else Cancelar

        AFP -> Sistema : cancelaOp()
        Sistema <-- Sistema : termina a execução

    end

else Informações Insuficientes ou Formato Inválido

    AFP <-- Sistema : mensagem de erro informando a falta de informações dadas pelo usuário, solicitando-as()
    alt Preenche

        AFP -> Sistema : completaInfoRelat()
        AFP <-- Sistema : continua a execução como se as informações tivessem sido dadas corretamente no início

    else Cancelar

        AFP -> Sistema : cancelaOp()
        Sistema <-- Sistema : termina a execução

    end

end
@enduml