@startuml
'rectangle "Gerente" as gerente
'rectangle "FolhaDePagamento" as folha
rectangle "Pagamento" as pagamento
rectangle "Funcionario" as funcionario
rectangle "Empresa" as empresa
'rectangle "ListaDeFuncionarios" as lista
'rectangle "Venda" as venda
'rectangle "Ponto" as ponto
rectangle "BaseDeDadosProjetos" as base
rectangle "Projeto" as projeto
label " " as ini

ini -down-> funcionario     : gerarRelatorioFuncionario()
funcionario -> funcionario  : 1 enviaInformacoes(tipoRelatorio, dataInico, dataFim)\n7 salvaRelatorio(relat)
funcionario -up-> projeto      : 2 projetos = getProj()
funcionario -left-> pagamento    : 3 pagamento = getPag()
funcionario -down-> empresa      : 4 relat = pedeRelatorio(tipoRelatorio, dataInico, dataFim, nomeFunc, projetos, pagamento)
empresa -down-> base             : 5 infos = getInfos(dataInico, dataFim, nomeFunc, projetos)
empresa -> empresa          : 6 fazRelatorio(infos)

@enduml