@startuml
'rectangle "Gerente" as gerente
'rectangle "FolhaDePagamento" as folha
'rectangle "Pagamento" as pagamento
rectangle "Funcionario" as funcionario
'rectangle "Empresa" as empresa
'rectangle "ListaDeFuncionarios" as lista
'rectangle "Venda" as venda
'rectangle "Ponto" as ponto
'rectangle "BaseDeDadosProjetos" as base
'rectangle "Projeto" as projeto
label " " as ini

ini -down-> funcionario     : gerarRelatorioFuncionario()
funcionario -> funcionario  : enviaInformacoes(tipoRelatorio, dataInico, dataFim)
@enduml